/* دادهٔ آنالیز SEO ذهن آتی — به‌روز: ۱۹ جولای ۲۰۲۶ / ۲۸ تیر ۱۴۰۵ */
window.ZEHNATI_SEO = {
  meta: {
    brand: "ذهن آتی",
    domain: "https://zehnati.ir/",
    manager: "دکتر زهرا جعفری",
    updatedAt: "2026-07-19",
    updatedAtFa: "۲۸ تیر ۱۴۰۵",
    phase: 1,
    phaseLabel: "فاز ۱ — ماه ۱: لندینگ‌های تجاری P0",
    week: 1,
    month: 1,
    planStartFa: "۱۴۰۵/۰۴/۲۰",
    planStartLabel: "۲۰ تیر ۱۴۰۵",
    planEndFa: "۱۴۰۵/۱۰/۱۹",
    planEndLabel: "۱۹ دی ۱۴۰۵",
    planMonths: 6,
    planWeeks: 26,
    planNote: "قرارداد ۶ ماهه — فاز ۰ پیش‌نیاز · فاز ۱–۶ = ماه ۱ تا ۶",
  },
  score: {
    overall: 55,
    label: "در حال پیشرفت — ماه ۱: لندینگ‌های P0",
    breakdown: [
      { id: "tech", name: "فنی", score: 50, max: 100 },
      { id: "onpage", name: "آن‌پیج", score: 70, max: 100 },
      { id: "content", name: "محتوا", score: 44, max: 100 },
      { id: "local", name: "محلی", score: 60, max: 100 },
      { id: "conversion", name: "تبدیل / Landing", score: 35, max: 100 },
    ],
  },
  kpis: [
    { label: "صفحات ایندکس (هدف ۶ماه)", current: "~۵", target: "۸۰+" },
    { label: "پست‌های بلاگ منتشرشده", current: "۳۳۲", target: "بهینه + CTA" },
    { label: "صفحات وردپرس", current: "۲۲", target: "۵۰+" },
    { label: "لندینگ P0 آماده‌شده", current: "۳", target: "۱۰+" },
  ],
  techStatus: [
    { id: "ssl", name: "HTTPS / SSL", status: "pass", detail: "فعال" },
    { id: "robots", name: "robots.txt", status: "pass", detail: "موجود؛ به sitemap_index.xml اشاره می‌کند (فعال)" },
    { id: "sitemap", name: "XML Sitemap", status: "pass", detail: "فعال (200) — sitemap_index.xml" },
    { id: "rankmath", name: "Rank Math", status: "pass", detail: "نصب شده" },
    { id: "analytics", name: "Analytics / GTM", status: "pass", detail: "GA4 از Rank Math — G-Y0GZ4B5T0Y" },
    { id: "litespeed", name: "LiteSpeed Cache", status: "pass", detail: "فعال" },
    { id: "h1", name: "H1 صفحه اصلی", status: "pass", detail: "مشاوره رایگان کنکور در ذهن آتی" },
    { id: "meta", name: "Meta Description", status: "pass", detail: "اختصاصی و بهینه — دیگر اسکرپ نیست" },
    { id: "about-h1", name: "H1 درباره ما", status: "pass", detail: "۱ H1 — درباره آکادمی ذهن آتی" },
    { id: "schema", name: "Schema محلی", status: "warn", detail: "LocalBusiness اصفهان هست؛ تهران/Person در ماه ۱" },
    { id: "landings", name: "Landingهای P0", status: "warn", detail: "ماه ۱ جاری — قیمت/آنلاین/شهر هنوز نه" },
  ],
  homepage: {
    titleNow: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر زهرا جعفری",
    titleTarget: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
    descNow:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    descTarget:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    h1Target: "مشاوره رایگان کنکور در ذهن آتی",
    schemas: ["ImageObject", "WebSite", "SearchAction", "WebPage", "Person", "Article"],
  },
  goldenKeywords: [
    { kw: "مشاوره رایگان کنکور", page: "/", status: "ok", note: "صفحه اصلی بهینه شد" },
    { kw: "مشاوره کنکور", page: "/مشاوره-کنکور/", status: "partial", note: "ماه ۱: کاهش ۱۷ H1 + هاب تجاری" },
    { kw: "بهترین مشاور کنکور اصفهان", page: "/بهترین-مشاور-کنکور-اصفهان/", status: "missing", note: "ماه ۱" },
    { kw: "برنامه ریزی کنکور", page: "/برنامه-ریزی-کنکور/", status: "partial", note: "ماه ۱–۲" },
    { kw: "مشاوره کنکور تجربی", page: "/مشاوره-کنکور-تجربی/", status: "ok", note: "موجود — اصلاح ساختار H1 در ماه ۱" },
    { kw: "قیمت مشاوره کنکور", page: "/قیمت-مشاوره-کنکور/", status: "missing", note: "ماه ۱ — اولویت" },
    { kw: "مشاوره آنلاین کنکور", page: "/مشاوره-آنلاین-کنکور/", status: "missing", note: "ماه ۱" },
    { kw: "چگونه پزشکی قبول شویم", page: "بلاگ", status: "partial", note: "ماه ۲–۳" },
    { kw: "ثبت نام کلاس کنکور", page: "/ثبت-نام/", status: "partial", note: "ماه ۱" },
    { kw: "دکتر زهرا جعفری", page: "/about/", status: "ok", note: "Meta/Title + ۱ H1 OK" },
  ],
  keywordBuckets: [
    { id: "P0", label: "حیاتی", count: 53, action: "لندینگ/هاب در ماه ۱–۲" },
    { id: "P1", label: "مهم", count: 90, action: "محتوا در ماه ۳–۵" },
    { id: "P2", label: "تکمیلی", count: 58, action: "بلاگ در ماه ۵–۶" },
    { id: "P3", label: "آینده", count: 5, action: "پس از قرارداد یا تمدید" },
  ],
  existingPages: [
    { url: "/", title: "خانه" },
    { url: "/about/", title: "درباره ما" },
    { url: "/contact-us/", title: "ارتباط با ما" },
    { url: "/academic-counseling/", title: "ویس آموزشی" },
    { url: "/top-consultants/", title: "مشاورین برتر" },
    { url: "/satisfaction/", title: "رضایتمندی" },
    { url: "/webinars/", title: "وبینارها" },
    { url: "/expert/", title: "فرم ثبت‌نام" },
  ],

  /* —— برنامه ۶ ماهه از ۱۴۰۵/۰۴/۲۰ —— */
  timeline: [
    {
      phase: 0,
      label: "فنی",
      months: 0,
      spanLabel: "پیش‌نیاز",
      dateRange: "تیر ۱۴۰۵",
      status: "done",
      summary: "زیربنای فنی سایت آماده شد (GSC، GA4، Sitemap، Rank Math، Home/About).",
    },
    {
      phase: 1,
      label: "لندینگ P0",
      months: 1,
      spanLabel: "ماه ۱",
      dateRange: "۲۰ تیر – ۱۹ مرداد",
      status: "active",
      summary: "قیف تجاری: قیمت، هاب مشاوره، آنلاین، شهر، نویسنده و Schema.",
    },
    {
      phase: 2,
      label: "پوشش P0 + Silo",
      months: 2,
      spanLabel: "ماه ۲",
      dateRange: "۲۰ مرداد – ۱۹ شهریور",
      status: "upcoming",
      summary: "تکمیل لندینگ‌های P0، homepage، مقالات ستون و لینک داخلی.",
    },
    {
      phase: 3,
      label: "محتوا و اعتبار",
      months: 3,
      spanLabel: "ماه ۳",
      dateRange: "۲۰ شهریور – ۱۹ مهر",
      status: "upcoming",
      summary: "خوشهٔ محتوایی P1، E-E-A-T، CTA و صفحات قابل استناد.",
    },
    {
      phase: 4,
      label: "محلی و تبدیل",
      months: 4,
      spanLabel: "ماه ۴",
      dateRange: "۲۰ مهر – ۱۹ آبان",
      status: "upcoming",
      summary: "GBP، سرعت صفحات پول‌ساز، امنیت، تصاویر و فرم‌ها.",
    },
    {
      phase: 5,
      label: "گسترش P1/P2",
      months: 5,
      spanLabel: "ماه ۵",
      dateRange: "۲۰ آبان – ۱۹ آذر",
      status: "upcoming",
      summary: "عمق Silo، کلمات مهم، رصد رقبا و لینک‌سازی امن.",
    },
    {
      phase: 6,
      label: "تثبیت و تحویل",
      months: 6,
      spanLabel: "ماه ۶",
      dateRange: "۲۰ آذر – ۱۹ دی",
      status: "upcoming",
      summary: "Audit نهایی، نگهداری، آموزش و بستهٔ تحویل ۶ماهه.",
    },
  ],

  phaseDetails: {
    0: {
      title: "فاز ۰ — فنی و آماده‌سازی",
      period: "پیش‌نیاز · تیر ۱۴۰۵",
      status: "done",
      goal: "سایت ایندکس‌پذیر، ابزار سنجش فعال، پایهٔ SEO آماده",
      actions: [
        {
          id: "p0-a1",
          priority: "critical",
          title: "رفع Sitemap 404",
          where: "Rank Math → Sitemap",
          why: "انجام شد — sitemap_index.xml = 200",
          done: true,
        },
        {
          id: "p0-a2",
          priority: "critical",
          title: "Submit Sitemap در GSC",
          where: "Google Search Console",
          why: "انجام شد — Success · صفحات کشف‌شده",
          done: true,
        },
        {
          id: "p0-a3",
          priority: "high",
          title: "اصلاح Title / Meta / H1 صفحه اصلی",
          where: "Rank Math Home",
          why: "انجام شد — مشاوره رایگان کنکور",
          done: true,
        },
        {
          id: "p0-a4",
          priority: "medium",
          title: "بهینه Meta برای /about/ و /contact-us/",
          where: "Rank Math",
          why: "انجام شد — Title/Meta + /about/ یک H1",
          done: true,
        },
        {
          id: "p0-a5",
          priority: "high",
          title: "نصب GA4 از Rank Math",
          where: "Rank Math → Analytics",
          why: "انجام شد — G-Y0GZ4B5T0Y در HTML",
          done: true,
        },
        {
          id: "p0-a6",
          priority: "medium",
          title: "کرون واقعی سرور (DISABLE_WP_CRON)",
          where: "cPanel Cron Jobs",
          why: "انجام شد — هر ۱۵ دقیقه wp-cron",
          done: true,
        },
      ],
      checklist: [
        { id: "w1-gsc", label: "ثبت Google Search Console", done: true },
        { id: "w1-ga4", label: "نصب Google Analytics 4", done: true },
        { id: "w1-sitemap", label: "رفع sitemap 404", done: true },
        { id: "w1-rankmath", label: "نصب/تنظیم Rank Math", done: true },
        { id: "w1-home-meta", label: "Title / Meta / H1 صفحه اصلی", done: true },
        { id: "w1-about", label: "بهینه درباره ما (Meta + ۱ H1)", done: true },
        { id: "w1-contact", label: "بهینه تماس با ما", done: true },
        { id: "w1-cron", label: "Cron واقعی روی هاست", done: true },
        { id: "w1-psi", label: "تست اولیه PageSpeed (ثبت شد)", done: true },
        { id: "w1-phase0-review", label: "بازبینی و بستن فاز ۰", done: true },
      ],
    },
    1: {
      title: "فاز ۱ — ماه ۱: لندینگ‌های تجاری P0",
      period: "ماه ۱ · ۲۰ تیر تا ۱۹ مرداد ۱۴۰۵",
      status: "active",
      goal: "قیف پول زنده: ۱۰+ لندینگ/هاب حیاتی قابل ایندکس",
      actions: [
        {
          id: "p1-a1",
          priority: "critical",
          title: "ساخت /قیمت-مشاوره-کنکور/",
          where: "صفحات → افزودن + Rank Math",
          why: "الان 404 — کلمه طلایی تجاری P0",
          done: false,
        },
        {
          id: "p1-a2",
          priority: "critical",
          title: "اصلاح هاب /مشاوره-کنکور/ (۱ H1 + محتوای تجاری)",
          where: "Elementor / قالب صفحه",
          why: "صفحه 200 است ولی ۱۷ H1 دارد",
          done: false,
        },
        {
          id: "p1-a3",
          priority: "high",
          title: "ساخت /مشاوره-آنلاین-کنکور/",
          where: "Landing جدید",
          why: "کلمه طلایی P0 — الان نیست",
          done: false,
        },
        {
          id: "p1-a4",
          priority: "high",
          title: "Landing اصفهان / بهترین مشاور کنکور اصفهان",
          where: "صفحه یا تبدیل مقاله",
          why: "سیگنال محلی اصفهان",
          done: false,
        },
        {
          id: "p1-a5",
          priority: "high",
          title: "Landing تهران + ثبت‌نام / پکیج",
          where: "وردپرس",
          why: "پوشش قیف تجاری",
          done: false,
        },
        {
          id: "p1-a6",
          priority: "medium",
          title: "کاهش H1 صفحه تجربی به ۱",
          where: "/مشاوره-کنکور-تجربی/",
          why: "الان ۱۷ H1 مثل آرشیو است",
          done: false,
        },
        {
          id: "p1-a7",
          priority: "high",
          title: "تعویض نویسنده fish-programmer → دکتر زهرا جعفری",
          where: "وردپرس کاربر / Rank Math",
          why: "E-E-A-T و Twitter author",
          done: false,
        },
        {
          id: "p1-a8",
          priority: "medium",
          title: "تکمیل Schema LocalBusiness + Person",
          where: "Rank Math Schema",
          why: "اصفهان کامل‌تر + تهران + Person دکتر جعفری",
          done: false,
        },
        {
          id: "p1-a9",
          priority: "high",
          title: "گزارش ماه ۱ + Submit صفحات جدید در GSC",
          where: "داشبورد + Search Console",
          why: "اثبات پیشرفت ماه اول قرارداد",
          done: false,
        },
      ],
      checklist: [
        { id: "p1-c1", label: "صفحه قیمت مشاوره کنکور (200)", done: false },
        { id: "p1-c2", label: "هاب مشاوره کنکور با ۱ H1", done: false },
        { id: "p1-c3", label: "لندینگ مشاوره آنلاین", done: false },
        { id: "p1-c4", label: "لندینگ اصفهان", done: false },
        { id: "p1-c5", label: "لندینگ تهران یا ثبت‌نام", done: false },
        { id: "p1-c6", label: "نویسنده سایت = دکتر جعفری", done: false },
        { id: "p1-c7", label: "Schema Local + Person", done: false },
        { id: "p1-c8", label: "Submit صفحات جدید در GSC", done: false },
        { id: "p1-c9", label: "گزارش ماه ۱ آماده", done: false },
      ],
    },
    2: {
      title: "فاز ۲ — ماه ۲: پوشش P0 کامل + Silo",
      period: "ماه ۲ · ۲۰ مرداد تا ۱۹ شهریور ۱۴۰۵",
      status: "upcoming",
      goal: "تقریباً همهٔ کلمات P0 صفحه داشته باشند + لینک داخلی ستون‌دار",
      actions: [
        {
          id: "p2-a1",
          priority: "high",
          title: "تقویت محتوای homepage (پوشش تجاری عمیق‌تر)",
          where: "صفحه اصلی Elementor",
          why: "هوم از نظر محتوا هنوز نازک است",
          done: false,
        },
        {
          id: "p2-a2",
          priority: "high",
          title: "مقاله P0: چگونه پزشکی قبول شویم (بازنویسی/تقویت)",
          where: "بلاگ",
          why: "کلمه طلایی اطلاعاتی",
          done: false,
        },
        {
          id: "p2-a3",
          priority: "high",
          title: "لینک داخلی از بلاگ به هاب‌های مشاوره/قیمت/رشته",
          where: "پست‌های کلیدی",
          why: "Silo و انتقال اعتبار",
          done: false,
        },
        {
          id: "p2-a4",
          priority: "medium",
          title: "هاب رشته ریاضی / انسانی تمیز (۱ H1)",
          where: "صفحات رشته",
          why: "هم‌تراز با تجربی",
          done: false,
        },
        {
          id: "p2-a5",
          priority: "medium",
          title: "برنامه ریزی کنکور + انتخاب رشته (صفحه اختصاصی)",
          where: "Landing یا اصلاح ریدایرکت‌های اشتباه",
          why: "URL تجاری نباید به مقاله نامرتبط برود",
          done: false,
        },
        {
          id: "p2-a6",
          priority: "high",
          title: "لندینگ‌های باقی‌مانده P0 (پکیج، کلاس آنلاین، …)",
          where: "وردپرس",
          why: "پوشش کامل ۵۳ کلمه حیاتی",
          done: false,
        },
        {
          id: "p2-a7",
          priority: "medium",
          title: "گزارش ماه ۲ + Audit سبک",
          where: "داشبورد + GSC",
          why: "مقایسه ایندکس و پوشش نسبت به ماه ۱",
          done: false,
        },
      ],
      checklist: [
        { id: "p2-c1", label: "Homepage محتوایی تقویت شد", done: false },
        { id: "p2-c2", label: "حداقل ۳ مقاله P0 بهینه", done: false },
        { id: "p2-c3", label: "لینک داخلی Silo روی ۱۰ پست کلیدی", done: false },
        { id: "p2-c4", label: "هاب رشته‌ها ساختار تمیز", done: false },
        { id: "p2-c5", label: "رفع ریدایرکت‌های اشتباه تجاری", done: false },
        { id: "p2-c6", label: "پوشش عمدهٔ لندینگ‌های P0", done: false },
        { id: "p2-c7", label: "گزارش ماه ۲", done: false },
      ],
    },
    3: {
      title: "فاز ۳ — ماه ۳: محتوا و اعتبار (E-E-A-T)",
      period: "ماه ۳ · ۲۰ شهریور تا ۱۹ مهر ۱۴۰۵",
      status: "upcoming",
      goal: "ترافیک اطلاعاتی → لید؛ نویسنده و اعتماد در همهٔ صفحات کلیدی",
      actions: [
        {
          id: "p3-a1",
          priority: "high",
          title: "۸–۱۲ مقاله P1 با CTA مشاوره رایگان",
          where: "بلاگ",
          why: "پر کردن قیف بالای تبدیل",
          done: false,
        },
        {
          id: "p3-a2",
          priority: "high",
          title: "بازنویسی مقالات ضعیف موجود (نه فقط پست جدید)",
          where: "آرشیو ۳۳۲ پست",
          why: "کیفیت > کمیت برای رتبه",
          done: false,
        },
        {
          id: "p3-a3",
          priority: "medium",
          title: "یکدست‌سازی بایو نویسنده و Person در صفحات کلیدی",
          where: "قالب / Rank Math",
          why: "سیگنال E-E-A-T",
          done: false,
        },
        {
          id: "p3-a4",
          priority: "medium",
          title: "صفحات قابل استناد + llms.txt (در صورت اسکوپ GEO)",
          where: "ریشه سایت / صفحات راهنما",
          why: "دیده‌شدن در جستجو و ابزارهای AI",
          done: false,
        },
        {
          id: "p3-a5",
          priority: "medium",
          title: "گزارش ماه ۳ (impression/CTR کلمات طلایی)",
          where: "GSC + داشبورد",
          why: "رصد رشد اطلاعاتی",
          done: false,
        },
      ],
      checklist: [
        { id: "p3-c1", label: "حداقل ۸ مقاله P1 منتشر/بهینه", done: false },
        { id: "p3-c2", label: "۵+ مقاله قدیمی بازنویسی عمیق", done: false },
        { id: "p3-c3", label: "بایو/نویسنده یکدست روی صفحات کلیدی", done: false },
        { id: "p3-c4", label: "llms.txt یا صفحات قابل استناد", done: false },
        { id: "p3-c5", label: "گزارش ماه ۳", done: false },
      ],
    },
    4: {
      title: "فاز ۴ — ماه ۴: محلی، سرعت و تبدیل",
      period: "ماه ۴ · ۲۰ مهر تا ۱۹ آبان ۱۴۰۵",
      status: "upcoming",
      goal: "Map Pack اصفهان + CWV بهتر روی URLهای پول‌ساز",
      actions: [
        {
          id: "p4-a1",
          priority: "high",
          title: "راه‌اندازی / تأیید Google Business اصفهان",
          where: "business.google.com",
          why: "Map Pack و اعتماد محلی",
          done: false,
        },
        {
          id: "p4-a2",
          priority: "medium",
          title: "شروع GBP تهران (یا زمان‌بندی تأیید)",
          where: "Google Business",
          why: "شعبه دوم",
          done: false,
        },
        {
          id: "p4-a3",
          priority: "medium",
          title: "هدرهای امنیتی پایه (HSTS, XFO, nosniff)",
          where: "LiteSpeed / هاست",
          why: "یافته technical audit",
          done: false,
        },
        {
          id: "p4-a4",
          priority: "medium",
          title: "بهینه تصاویر (alt + فشرده‌سازی LCP)",
          where: "مدیا وردپرس",
          why: "۱۵/۱۶ تصویر بدون alt روی هوم",
          done: false,
        },
        {
          id: "p4-a5",
          priority: "high",
          title: "PageSpeed/CWV روی ۳–۵ URL پول‌ساز",
          where: "PSI + LiteSpeed",
          why: "سرعت = رتبه و تبدیل",
          done: false,
        },
        {
          id: "p4-a6",
          priority: "medium",
          title: "بهینه فرم CTA + FAQ Schema صفحات فروش",
          where: "لندینگ‌ها",
          why: "افزایش نرخ درخواست مشاوره",
          done: false,
        },
        {
          id: "p4-a7",
          priority: "medium",
          title: "گزارش ماه ۴ (لوکال + سرعت قبل/بعد)",
          where: "داشبورد",
          why: "اثبات بهبود فنی ماهانه",
          done: false,
        },
      ],
      checklist: [
        { id: "p4-c1", label: "GBP اصفهان ثبت/تأیید شده", done: false },
        { id: "p4-c2", label: "هدرهای امنیتی فعال", done: false },
        { id: "p4-c3", label: "alt تصاویر صفحه اصلی", done: false },
        { id: "p4-c4", label: "PageSpeed ثبت روی URLهای کلیدی", done: false },
        { id: "p4-c5", label: "FAQ/فرم لندینگ‌های اصلی", done: false },
        { id: "p4-c6", label: "گزارش ماه ۴", done: false },
      ],
    },
    5: {
      title: "فاز ۵ — ماه ۵: گسترش P1/P2 و رقابت",
      period: "ماه ۵ · ۲۰ آبان تا ۱۹ آذر ۱۴۰۵",
      status: "upcoming",
      goal: "عمق Silo و دفاع برند روی کلمات مهم",
      actions: [
        {
          id: "p5-a1",
          priority: "high",
          title: "۱۰–۱۵ کلمه P1 اولویت‌دار → صفحه یا بلاگ",
          where: "وردپرس",
          why: "پیشروی سیستماتیک در ۹۰ کلمه مهم",
          done: false,
        },
        {
          id: "p5-a2",
          priority: "medium",
          title: "محتوای مقایسه‌ای/«بهترین…» فقط با ادعای قابل دفاع",
          where: "لندینگ یا بلاگ",
          why: "کلمات commercial بدون ریسک ادعا",
          done: false,
        },
        {
          id: "p5-a3",
          priority: "medium",
          title: "لینک‌سازی محدود و امن (پروفایل برند / دایرکتوری معتبر)",
          where: "خارج از سایت",
          why: "نه رپورتاژ اسپم",
          done: false,
        },
        {
          id: "p5-a4",
          priority: "high",
          title: "رصد رقبا روی ۱۰–۱۵ کلمه طلایی",
          where: "GSC + SERP",
          why: "تنظیم اولویت ماه ۶",
          done: false,
        },
        {
          id: "p5-a5",
          priority: "medium",
          title: "گزارش ماه ۵ + جدول رتبه/impression",
          where: "داشبورد",
          why: "شفافیت برای تمدید/جمع‌بندی",
          done: false,
        },
      ],
      checklist: [
        { id: "p5-c1", label: "۱۰+ صفحه/مقاله P1 جدید یا بهینه", done: false },
        { id: "p5-c2", label: "حداقل ۲ دارایی برند/لینک معتبر", done: false },
        { id: "p5-c3", label: "جدول رصد رقبا به‌روز", done: false },
        { id: "p5-c4", label: "گزارش ماه ۵", done: false },
      ],
    },
    6: {
      title: "فاز ۶ — ماه ۶: تثبیت و تحویل",
      period: "ماه ۶ · ۲۰ آذر تا ۱۹ دی ۱۴۰۵",
      status: "upcoming",
      goal: "سیستم پایدار + بستهٔ نهایی قرارداد",
      actions: [
        {
          id: "p6-a1",
          priority: "high",
          title: "Audit کامل مجدد + مقایسه با baseline جولای ۲۰۲۶",
          where: "Cursor /seo audit + داشبورد",
          why: "اثبات پیشرفت ۶ ماهه",
          done: false,
        },
        {
          id: "p6-a2",
          priority: "high",
          title: "چک‌لیست نگهداری هفتگی/ماهانه برای تیم داخلی",
          where: "مستند تحویل",
          why: "ادامه بدون وابستگی کامل",
          done: false,
        },
        {
          id: "p6-a3",
          priority: "medium",
          title: "بستن بدهی‌های فنی باقی‌مانده",
          where: "وردپرس / هاست",
          why: "پاکسازی قبل از پایان قرارداد",
          done: false,
        },
        {
          id: "p6-a4",
          priority: "high",
          title: "گزارش ۶ماهه + پیشنهاد فاز بعدی",
          where: "داشبورد + PDF/Markdown",
          why: "تحویل رسمی قرارداد",
          done: false,
        },
      ],
      checklist: [
        { id: "p6-c1", label: "Audit نهایی ثبت شد", done: false },
        { id: "p6-c2", label: "چک‌لیست نگهداری تحویل شد", done: false },
        { id: "p6-c3", label: "بدهی فنی اولویت‌دار بسته شد", done: false },
        { id: "p6-c4", label: "گزارش نهایی ۶ماهه", done: false },
      ],
    },
  },

  metaTargets: [
    {
      page: "صفحه اصلی",
      url: "/",
      title: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
      description:
        "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
      h1: "مشاوره رایگان کنکور در ذهن آتی",
    },
    {
      page: "درباره ما",
      url: "/about/",
      title: "درباره آکادمی ذهن آتی | دکتر زهرا جعفری",
      description:
        "آکادمی مشاوره کنکور ذهن آتی با مدیریت دکتر زهرا جعفری. ۲۰۰۰+ قبولی و ۵۰۰ رتبه دو و سه‌رقمی. اپلیکیشن اختصاصی.",
      h1: "درباره آکادمی ذهن آتی",
    },
    {
      page: "تماس",
      url: "/contact-us/",
      title: "تماس با ذهن آتی | مشاوره رایگان کنکور",
      description:
        "تماس با آکادمی ذهن آتی: ۰۲۱-۲۸۴۲۷۲۵۹. شعب اصفهان (وحید) و تهران (میدان فاطمی). مشاوره رایگان آنلاین.",
      h1: "تماس با ما",
    },
  ],
};

/* آرایه‌های تخت برای سازگاری با رندرر */
(function expandPhaseLists(D) {
  D.actions = [];
  const phases = Object.keys(D.phaseDetails || {})
    .map(Number)
    .sort((a, b) => a - b);
  for (const p of phases) {
    const det = D.phaseDetails[p];
    if (!det) continue;
    for (const a of det.actions || []) {
      D.actions.push(Object.assign({ phase: p }, a));
    }
  }
  D.week1Checklist = (D.phaseDetails[0] && D.phaseDetails[0].checklist) || [];
})(window.ZEHNATI_SEO);
