/* دادهٔ آنالیز SEO ذهن آتی — به‌روز: ۱۹ جولای ۲۰۲۶ / ۲۸ تیر ۱۴۰۵ */
window.ZEHNATI_SEO = {
  meta: {
    brand: "ذهن آتی",
    domain: "https://zehnati.ir/",
    manager: "دکتر زهرا جعفری",
    updatedAt: "2026-07-20",
    updatedAtFa: "۲۸ تیر ۱۴۰۵",
    phase: 1,
    phaseLabel: "فاز ۱ — ماه ۱: لندینگ‌های تجاری P0",
    week: 1,
    month: 1,
    planStartFa: "۱۴۰۵/۰۴/۲۰",
    planStartLabel: "۲۰ تیر ۱۴۰۵",
    planEndFa: "۱۴۰۵/۱۱/۱۹",
    planEndLabel: "۱۹ بهمن ۱۴۰۵",
    planMonths: 7,
    planWeeks: 30,
    planNote: "قرارداد ۷ ماهه — فاز ۰ پیش‌نیاز · فاز ۱–۷ = ماه ۱ تا ۷ · پوشش ۲۰۶ کیورد",
    keywordTotal: 206,
  },
  score: {
    overall: 55,
    label: "در حال پیشرفت — ماه ۱: لندینگ‌های P0",
    breakdown: [
      { id: "tech", name: "فنی", score: 50, max: 100 },
      { id: "onpage", name: "آن‌پیج", score: 70, max: 100 },
      { id: "content", name: "محتوا", score: 44, max: 100 },
      { id: "local", name: "محلی", score: 60, max: 100 },
      { id: "conversion", name: "تبدیل / Landing", score: 35, max: 100 },
    ],
  },
  kpis: [
    { label: "کیورد پوشش‌داده‌شده (از ۲۰۶)", current: "~۱۵", target: "۲۰۶" },
    { label: "صفحات ایندکس (هدف ۷ماه)", current: "~۵", target: "۱۰۰+" },
    { label: "پست‌های بلاگ", current: "۳۳۲", target: "بهینه + CTA" },
    { label: "لندینگ/هاب P0", current: "۳", target: "۲۵+ URL" },
  ],
  techStatus: [
    { id: "ssl", name: "HTTPS / SSL", status: "pass", detail: "فعال" },
    { id: "robots", name: "robots.txt", status: "pass", detail: "موجود؛ به sitemap_index.xml اشاره می‌کند (فعال)" },
    { id: "sitemap", name: "XML Sitemap", status: "pass", detail: "sitemap_index.xml = 200 (با و بدون www) · ۶ زیرنقشه" },
    { id: "rankmath", name: "Rank Math", status: "pass", detail: "نصب شده" },
    { id: "analytics", name: "Analytics / GTM", status: "pass", detail: "GA4 از Rank Math — G-Y0GZ4B5T0Y" },
    { id: "litespeed", name: "LiteSpeed Cache", status: "pass", detail: "فعال" },
    { id: "h1", name: "H1 صفحه اصلی", status: "pass", detail: "مشاوره رایگان کنکور در ذهن آتی" },
    { id: "meta", name: "Meta Description", status: "pass", detail: "اختصاصی و بهینه — دیگر اسکرپ نیست" },
    { id: "about-h1", name: "H1 درباره ما", status: "pass", detail: "۱ H1 — درباره آکادمی ذهن آتی" },
    { id: "schema", name: "Schema محلی", status: "warn", detail: "LocalBusiness اصفهان هست؛ تهران/Person در ماه ۱" },
    { id: "landings", name: "Landingهای P0", status: "warn", detail: "قیمت 200 شد · آنلاین/شهر باقی مانده" },
  ],
  homepage: {
    titleNow: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر زهرا جعفری",
    titleTarget: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
    descNow:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    descTarget:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    h1Target: "مشاوره رایگان کنکور در ذهن آتی",
    schemas: ["ImageObject", "WebSite", "SearchAction", "WebPage", "Person", "Article"],
  },
  goldenKeywords: [
    { kw: "مشاوره رایگان کنکور", page: "/", status: "ok", note: "صفحه اصلی بهینه شد" },
    { kw: "مشاوره کنکور", page: "/مشاوره-کنکور/", status: "mapped", note: "ماه ۱ — ۱ H1 + هاب تجاری" },
    { kw: "بهترین مشاور کنکور اصفهان", page: "/بهترین-مشاور-کنکور-اصفهان/", status: "missing", note: "ماه ۱" },
    { kw: "برنامه ریزی کنکور", page: "/برنامه-ریزی-کنکور/", status: "partial", note: "ماه ۱–۲" },
    { kw: "مشاوره کنکور تجربی", page: "/مشاوره-کنکور-تجربی/", status: "ok", note: "موجود — اصلاح ساختار H1 در ماه ۱" },
    { kw: "قیمت مشاوره کنکور", page: "/قیمت-مشاوره-کنکور/", status: "mapped", note: "ماه ۱ — 200" },
    { kw: "مشاوره آنلاین کنکور", page: "/مشاوره-آنلاین-کنکور/", status: "missing", note: "ماه ۱" },
    { kw: "چگونه پزشکی قبول شویم", page: "بلاگ", status: "partial", note: "ماه ۲–۳" },
    { kw: "ثبت نام کلاس کنکور", page: "/ثبت-نام/", status: "partial", note: "ماه ۱" },
    { kw: "دکتر زهرا جعفری", page: "/about/", status: "ok", note: "Meta/Title + ۱ H1 OK" },
  ],
  /* پوشش کامل ۲۰۶ کیورد در ۷ ماه (هاب مشترک مجاز است) */
  keywordBuckets: [
    { id: "P0", label: "حیاتی", count: 53, action: "ماه ۱–۲ · هدف پوشش ۵۳/۵۳" },
    { id: "P1", label: "مهم", count: 90, action: "ماه ۳–۶ · ۳۰+۱۵+۳۰+۱۵" },
    { id: "P2", label: "تکمیلی", count: 58, action: "ماه ۶–۷ · ۳۰+۲۸" },
    { id: "P3", label: "آینده‌نزدیک", count: 5, action: "ماه ۷ · ۵/۵" },
  ],
  keywordCoveragePlan: [
    { month: 1, phase: 1, p0: 25, p1: 0, p2: 0, p3: 0, note: "لندینگ/هاب تجاری حیاتی" },
    { month: 2, phase: 2, p0: 28, p1: 0, p2: 0, p3: 0, note: "تکمیل P0 + Silo" },
    { month: 3, phase: 3, p0: 0, p1: 30, p2: 0, p3: 0, note: "دستهٔ اول P1" },
    { month: 4, phase: 4, p0: 0, p1: 15, p2: 0, p3: 0, note: "لوکال/سرعت + P1 سبک" },
    { month: 5, phase: 5, p0: 0, p1: 30, p2: 0, p3: 0, note: "دستهٔ دوم P1" },
    { month: 6, phase: 6, p0: 0, p1: 15, p2: 30, p3: 0, note: "باقی P1 + شروع P2" },
    { month: 7, phase: 7, p0: 0, p1: 0, p2: 28, p3: 5, note: "تکمیل P2/P3 + تحویل" },
  ],
  existingPages: [
    { url: "/", title: "خانه" },
    { url: "/about/", title: "درباره ما" },
    { url: "/contact-us/", title: "ارتباط با ما" },
    { url: "/academic-counseling/", title: "ویس آموزشی" },
    { url: "/top-consultants/", title: "مشاورین برتر" },
    { url: "/satisfaction/", title: "رضایتمندی" },
    { url: "/webinars/", title: "وبینارها" },
    { url: "/expert/", title: "فرم ثبت‌نام" },
  ],

  /* —— برنامه ۷ ماهه از ۱۴۰۵/۰۴/۲۰ —— */
  timeline: [
    {
      phase: 0,
      label: "فنی",
      months: 0,
      spanLabel: "پیش‌نیاز",
      dateRange: "تیر ۱۴۰۵",
      status: "done",
      summary: "زیربنای فنی سایت آماده شد (GSC، GA4، Sitemap، Rank Math، Home/About).",
    },
    {
      phase: 1,
      label: "لندینگ P0",
      months: 1,
      spanLabel: "ماه ۱",
      dateRange: "۲۰ تیر – ۱۹ مرداد",
      status: "active",
      summary: "۲۵ کیورد P0 · قیمت، هاب مشاوره، آنلاین، شهر، نویسنده، Schema.",
    },
    {
      phase: 2,
      label: "تکمیل P0",
      months: 2,
      spanLabel: "ماه ۲",
      dateRange: "۲۰ مرداد – ۱۹ شهریور",
      status: "upcoming",
      summary: "۲۸ کیورد P0 باقی · homepage، Silo، هاب رشته‌ها — جمع P0 = ۵۳/۵۳.",
    },
    {
      phase: 3,
      label: "محتوای P1-۱",
      months: 3,
      spanLabel: "ماه ۳",
      dateRange: "۲۰ شهریور – ۱۹ مهر",
      status: "upcoming",
      summary: "۳۰ کیورد P1 · مقالات/صفحات + CTA و E-E-A-T.",
    },
    {
      phase: 4,
      label: "محلی + P1",
      months: 4,
      spanLabel: "ماه ۴",
      dateRange: "۲۰ مهر – ۱۹ آبان",
      status: "upcoming",
      summary: "GBP/CWV/امنیت + ۱۵ کیورد P1 سبک.",
    },
    {
      phase: 5,
      label: "محتوای P1-۲",
      months: 5,
      spanLabel: "ماه ۵",
      dateRange: "۲۰ آبان – ۱۹ آذر",
      status: "upcoming",
      summary: "۳۰ کیورد P1 · رصد رقبا و لینک‌سازی امن.",
    },
    {
      phase: 6,
      label: "P1 باقی + P2",
      months: 6,
      spanLabel: "ماه ۶",
      dateRange: "۲۰ آذر – ۱۹ دی",
      status: "upcoming",
      summary: "۱۵ کیورد P1 باقی + ۳۰ کیورد P2 — جمع P1 = ۹۰/۹۰.",
    },
    {
      phase: 7,
      label: "P2/P3 + تحویل",
      months: 7,
      spanLabel: "ماه ۷",
      dateRange: "۲۰ دی – ۱۹ بهمن",
      status: "upcoming",
      summary: "۲۸ کیورد P2 + ۵ کیورد P3 · Audit نهایی و بستهٔ تحویل — ۲۰۶/۲۰۶.",
    },
  ],

  phaseDetails: {
    0: {
      title: "فاز ۰ — فنی و آماده‌سازی",
      period: "پیش‌نیاز · تیر ۱۴۰۵",
      status: "done",
      goal: "سایت ایندکس‌پذیر، ابزار سنجش فعال، پایهٔ SEO آماده",
      kwTarget: { p0: 0, p1: 0, p2: 0, p3: 0, total: 0 },
      actions: [
        {
          id: "p0-a1",
          priority: "critical",
          title: "رفع Sitemap 404",
          where: "Rank Math → Sitemap + Permalinks + LiteSpeed exclude",
          why: "درست شد — sitemap_index.xml = 200",
          done: true,
        },
        {
          id: "p0-a2",
          priority: "critical",
          title: "Submit Sitemap در GSC",
          where: "Google Search Console",
          why: "انجام شد — Success · صفحات کشف‌شده",
          done: true,
        },
        {
          id: "p0-a3",
          priority: "high",
          title: "اصلاح Title / Meta / H1 صفحه اصلی",
          where: "Rank Math Home",
          why: "انجام شد — مشاوره رایگان کنکور",
          done: true,
        },
        {
          id: "p0-a4",
          priority: "medium",
          title: "بهینه Meta برای /about/ و /contact-us/",
          where: "Rank Math",
          why: "انجام شد — Title/Meta + /about/ یک H1",
          done: true,
        },
        {
          id: "p0-a5",
          priority: "high",
          title: "نصب GA4 از Rank Math",
          where: "Rank Math → Analytics",
          why: "انجام شد — G-Y0GZ4B5T0Y در HTML",
          done: true,
        },
        {
          id: "p0-a6",
          priority: "medium",
          title: "کرون واقعی سرور (DISABLE_WP_CRON)",
          where: "cPanel Cron Jobs",
          why: "انجام شد — هر ۱۵ دقیقه wp-cron",
          done: true,
        },
      ],
      checklist: [
        { id: "w1-gsc", label: "ثبت Google Search Console", done: true },
        { id: "w1-ga4", label: "نصب Google Analytics 4", done: true },
        { id: "w1-sitemap", label: "رفع sitemap 404", done: true },
        { id: "w1-rankmath", label: "نصب/تنظیم Rank Math", done: true },
        { id: "w1-home-meta", label: "Title / Meta / H1 صفحه اصلی", done: true },
        { id: "w1-about", label: "بهینه درباره ما (Meta + ۱ H1)", done: true },
        { id: "w1-contact", label: "بهینه تماس با ما", done: true },
        { id: "w1-cron", label: "Cron واقعی روی هاست", done: true },
        { id: "w1-psi", label: "تست اولیه PageSpeed (ثبت شد)", done: true },
        { id: "w1-phase0-review", label: "بازبینی و بستن فاز ۰", done: true },
      ],
    },
    1: {
      title: "فاز ۱ — ماه ۱: لندینگ‌های تجاری P0",
      period: "ماه ۱ · ۲۰ تیر تا ۱۹ مرداد ۱۴۰۵",
      status: "active",
      goal: "قیف پول زنده · پوشش ۲۵ کیورد P0 از طریق لندینگ/هاب",
      kwTarget: { p0: 25, p1: 0, p2: 0, p3: 0, total: 25 },
      actions: [
        {
          id: "p1-a1",
          priority: "critical",
          title: "ساخت /قیمت-مشاوره-کنکور/",
          where: "صفحات → افزودن + Rank Math",
          why: "منتشر شد — HTTP 200",
          done: true,
        },
        {
          id: "p1-a2",
          priority: "critical",
          title: "اصلاح هاب /مشاوره-کنکور/ (۱ H1 + محتوای تجاری)",
          where: "Elementor / قالب صفحه",
          why: "انجام شد — ۱ H1 + هاب تجاری",
          done: true,
        },
        {
          id: "p1-a3",
          priority: "high",
          title: "ساخت /مشاوره-آنلاین-کنکور/",
          where: "Landing جدید",
          why: "کلمه طلایی P0 — الان نیست",
          done: false,
        },
        {
          id: "p1-a4",
          priority: "high",
          title: "Landing اصفهان / بهترین مشاور کنکور اصفهان",
          where: "صفحه یا تبدیل مقاله",
          why: "سیگنال محلی اصفهان",
          done: false,
        },
        {
          id: "p1-a5",
          priority: "high",
          title: "Landing تهران + ثبت‌نام / پکیج",
          where: "وردپرس",
          why: "پوشش قیف تجاری",
          done: false,
        },
        {
          id: "p1-a6",
          priority: "medium",
          title: "کاهش H1 صفحه تجربی به ۱",
          where: "/مشاوره-کنکور-تجربی/",
          why: "الان ۱۷ H1 مثل آرشیو است",
          done: false,
        },
        {
          id: "p1-a7",
          priority: "high",
          title: "تعویض نویسنده fish-programmer → دکتر زهرا جعفری",
          where: "وردپرس کاربر / Rank Math",
          why: "E-E-A-T و Twitter author",
          done: false,
        },
        {
          id: "p1-a8",
          priority: "medium",
          title: "تکمیل Schema LocalBusiness + Person",
          where: "Rank Math Schema",
          why: "اصفهان کامل‌تر + تهران + Person دکتر جعفری",
          done: false,
        },
        {
          id: "p1-a9",
          priority: "high",
          title: "نقشهٔ پوشش: ۲۵ کیورد P0 ماه ۱ در CSV علامت‌گذاری شود",
          where: "keywords.csv / داشبورد",
          why: "هر کیورد → URL هدف مشخص",
          done: false,
        },
        {
          id: "p1-a10",
          priority: "high",
          title: "گزارش ماه ۱ + Submit صفحات جدید در GSC",
          where: "داشبورد + Search Console",
          why: "اثبات پیشرفت ماه اول · هدف تجمعی ۲۵/۲۰۶",
          done: false,
        },
      ],
      checklist: [
        { id: "p1-c1", label: "صفحه قیمت مشاوره کنکور (200)", done: true },
        { id: "p1-c2", label: "هاب مشاوره کنکور با ۱ H1", done: true },
        { id: "p1-c3", label: "لندینگ مشاوره آنلاین", done: false },
        { id: "p1-c4", label: "لندینگ اصفهان", done: false },
        { id: "p1-c5", label: "لندینگ تهران یا ثبت‌نام", done: false },
        { id: "p1-c6", label: "نویسنده سایت = دکتر جعفری", done: false },
        { id: "p1-c7", label: "Schema Local + Person", done: false },
        { id: "p1-c8", label: "۲۵ کیورد P0 ماه ۱ به URL وصل شدند", done: false },
        { id: "p1-c9", label: "Submit صفحات جدید در GSC", done: false },
        { id: "p1-c10", label: "گزارش ماه ۱ آماده", done: false },
      ],
    },
    2: {
      title: "فاز ۲ — ماه ۲: تکمیل P0 + Silo",
      period: "ماه ۲ · ۲۰ مرداد تا ۱۹ شهریور ۱۴۰۵",
      status: "upcoming",
      goal: "۲۸ کیورد P0 باقی → جمع P0 = ۵۳/۵۳ + لینک داخلی ستون‌دار",
      kwTarget: { p0: 28, p1: 0, p2: 0, p3: 0, total: 28 },
      actions: [
        {
          id: "p2-a1",
          priority: "high",
          title: "تقویت محتوای homepage (پوشش تجاری عمیق‌تر)",
          where: "صفحه اصلی Elementor",
          why: "هوم از نظر محتوا هنوز نازک است",
          done: false,
        },
        {
          id: "p2-a2",
          priority: "high",
          title: "مقاله/صفحه P0: چگونه پزشکی قبول شویم (+ خوشهٔ مرتبط)",
          where: "بلاگ / لندینگ",
          why: "کلمه طلایی اطلاعاتی داخل باکت P0",
          done: false,
        },
        {
          id: "p2-a3",
          priority: "high",
          title: "لینک داخلی از بلاگ به هاب‌های مشاوره/قیمت/رشته",
          where: "پست‌های کلیدی",
          why: "Silo و انتقال اعتبار",
          done: false,
        },
        {
          id: "p2-a4",
          priority: "medium",
          title: "هاب رشته ریاضی / انسانی تمیز (۱ H1)",
          where: "صفحات رشته",
          why: "هم‌تراز با تجربی",
          done: false,
        },
        {
          id: "p2-a5",
          priority: "medium",
          title: "برنامه ریزی کنکور + انتخاب رشته (صفحه اختصاصی)",
          where: "Landing یا اصلاح ریدایرکت‌های اشتباه",
          why: "URL تجاری نباید به مقاله نامرتبط برود",
          done: false,
        },
        {
          id: "p2-a6",
          priority: "critical",
          title: "بستن ۲۸ کیورد P0 باقی‌مانده (پکیج، کلاس آنلاین، پایه، …)",
          where: "وردپرس + keywords.csv",
          why: "پوشش کامل ۵۳ کلمه حیاتی تا پایان ماه ۲",
          done: false,
        },
        {
          id: "p2-a7",
          priority: "medium",
          title: "گزارش ماه ۲ + Audit سبک · تجمعی ۵۳/۲۰۶",
          where: "داشبورد + GSC",
          why: "P0 بسته شد؛ آماده ورود به P1",
          done: false,
        },
      ],
      checklist: [
        { id: "p2-c1", label: "Homepage محتوایی تقویت شد", done: false },
        { id: "p2-c2", label: "حداقل ۳ مقاله/صفحه ستون P0", done: false },
        { id: "p2-c3", label: "لینک داخلی Silo روی ۱۰ پست کلیدی", done: false },
        { id: "p2-c4", label: "هاب رشته‌ها ساختار تمیز", done: false },
        { id: "p2-c5", label: "رفع ریدایرکت‌های اشتباه تجاری", done: false },
        { id: "p2-c6", label: "P0 کامل: ۵۳/۵۳ کیورد به URL وصل", done: false },
        { id: "p2-c7", label: "گزارش ماه ۲", done: false },
      ],
    },
    3: {
      title: "فاز ۳ — ماه ۳: محتوای P1 (دسته ۱)",
      period: "ماه ۳ · ۲۰ شهریور تا ۱۹ مهر ۱۴۰۵",
      status: "upcoming",
      goal: "۳۰ کیورد P1 · صفحه یا بلاگ اختصاصی/خوشه‌ای + CTA",
      kwTarget: { p0: 0, p1: 30, p2: 0, p3: 0, total: 30 },
      actions: [
        {
          id: "p3-a1",
          priority: "critical",
          title: "۳۰ کیورد P1 دستهٔ اول → صفحه یا مقاله (با CTA)",
          where: "بلاگ / صفحات",
          why: "شروع پوشش ۹۰ کلمه مهم · هدف ماه: ۳۰",
          done: false,
        },
        {
          id: "p3-a2",
          priority: "high",
          title: "بازنویسی مقالات ضعیف هم‌پوشان با همان ۳۰ کیورد",
          where: "آرشیو ۳۳۲ پست",
          why: "کیفیت > کمیت؛ جلوگیری از کنیبال",
          done: false,
        },
        {
          id: "p3-a3",
          priority: "medium",
          title: "یکدست‌سازی بایو نویسنده و Person در صفحات جدید",
          where: "قالب / Rank Math",
          why: "سیگنال E-E-A-T",
          done: false,
        },
        {
          id: "p3-a4",
          priority: "medium",
          title: "صفحات قابل استناد + llms.txt (در صورت اسکوپ GEO)",
          where: "ریشه سایت / صفحات راهنما",
          why: "دیده‌شدن در جستجو و ابزارهای AI",
          done: false,
        },
        {
          id: "p3-a5",
          priority: "high",
          title: "به‌روزرسانی وضعیت ۳۰ کیورد در CSV + گزارش ماه ۳",
          where: "keywords.csv + GSC",
          why: "تجمعی ۸۳/۲۰۶ (۵۳ P0 + ۳۰ P1)",
          done: false,
        },
      ],
      checklist: [
        { id: "p3-c1", label: "۳۰ کیورد P1 ماه ۳ پوشش داده شد", done: false },
        { id: "p3-c2", label: "بازنویسی هم‌پوشان برای همان دسته", done: false },
        { id: "p3-c3", label: "بایو/نویسنده یکدست روی صفحات جدید", done: false },
        { id: "p3-c4", label: "llms.txt یا صفحات قابل استناد", done: false },
        { id: "p3-c5", label: "گزارش ماه ۳ · تجمعی ۸۳/۲۰۶", done: false },
      ],
    },
    4: {
      title: "فاز ۴ — ماه ۴: محلی، سرعت + ۱۵ کیورد P1",
      period: "ماه ۴ · ۲۰ مهر تا ۱۹ آبان ۱۴۰۵",
      status: "upcoming",
      goal: "Map Pack / CWV + ۱۵ کیورد P1 سبک",
      kwTarget: { p0: 0, p1: 15, p2: 0, p3: 0, total: 15 },
      actions: [
        {
          id: "p4-a1",
          priority: "high",
          title: "راه‌اندازی / تأیید Google Business اصفهان",
          where: "business.google.com",
          why: "Map Pack و اعتماد محلی",
          done: false,
        },
        {
          id: "p4-a2",
          priority: "medium",
          title: "شروع GBP تهران (یا زمان‌بندی تأیید)",
          where: "Google Business",
          why: "شعبه دوم",
          done: false,
        },
        {
          id: "p4-a3",
          priority: "medium",
          title: "هدرهای امنیتی پایه (HSTS, XFO, nosniff)",
          where: "LiteSpeed / هاست",
          why: "یافته technical audit",
          done: false,
        },
        {
          id: "p4-a4",
          priority: "medium",
          title: "بهینه تصاویر (alt + فشرده‌سازی LCP)",
          where: "مدیا وردپرس",
          why: "۱۵/۱۶ تصویر بدون alt روی هوم",
          done: false,
        },
        {
          id: "p4-a5",
          priority: "high",
          title: "PageSpeed/CWV روی ۳–۵ URL پول‌ساز",
          where: "PSI + LiteSpeed",
          why: "سرعت = رتبه و تبدیل",
          done: false,
        },
        {
          id: "p4-a6",
          priority: "medium",
          title: "بهینه فرم CTA + FAQ Schema صفحات فروش",
          where: "لندینگ‌ها",
          why: "افزایش نرخ درخواست مشاوره",
          done: false,
        },
        {
          id: "p4-a7",
          priority: "high",
          title: "۱۵ کیورد P1 ماه ۴ (صفحه کوتاه یا تقویت موجود)",
          where: "وردپرس + keywords.csv",
          why: "ادامه پوشش P1 بدون توقف در ماه فنی",
          done: false,
        },
        {
          id: "p4-a8",
          priority: "medium",
          title: "گزارش ماه ۴ · تجمعی ۹۸/۲۰۶",
          where: "داشبورد",
          why: "لوکال + سرعت + ۱۵ P1",
          done: false,
        },
      ],
      checklist: [
        { id: "p4-c1", label: "GBP اصفهان ثبت/تأیید شده", done: false },
        { id: "p4-c2", label: "هدرهای امنیتی فعال", done: false },
        { id: "p4-c3", label: "alt تصاویر صفحه اصلی", done: false },
        { id: "p4-c4", label: "PageSpeed ثبت روی URLهای کلیدی", done: false },
        { id: "p4-c5", label: "FAQ/فرم لندینگ‌های اصلی", done: false },
        { id: "p4-c6", label: "۱۵ کیورد P1 ماه ۴ پوشش شد", done: false },
        { id: "p4-c7", label: "گزارش ماه ۴ · ۹۸/۲۰۶", done: false },
      ],
    },
    5: {
      title: "فاز ۵ — ماه ۵: محتوای P1 (دسته ۲)",
      period: "ماه ۵ · ۲۰ آبان تا ۱۹ آذر ۱۴۰۵",
      status: "upcoming",
      goal: "۳۰ کیورد P1 · رصد رقبا و لینک‌سازی امن",
      kwTarget: { p0: 0, p1: 30, p2: 0, p3: 0, total: 30 },
      actions: [
        {
          id: "p5-a1",
          priority: "critical",
          title: "۳۰ کیورد P1 دستهٔ دوم → صفحه یا بلاگ",
          where: "وردپرس",
          why: "پیشروی سیستماتیک · تجمعی بعد از ماه: ۱۲۸/۲۰۶",
          done: false,
        },
        {
          id: "p5-a2",
          priority: "medium",
          title: "محتوای مقایسه‌ای/«بهترین…» فقط با ادعای قابل دفاع",
          where: "لندینگ یا بلاگ",
          why: "کلمات commercial بدون ریسک ادعا",
          done: false,
        },
        {
          id: "p5-a3",
          priority: "medium",
          title: "لینک‌سازی محدود و امن (پروفایل برند / دایرکتوری معتبر)",
          where: "خارج از سایت",
          why: "نه رپورتاژ اسپم",
          done: false,
        },
        {
          id: "p5-a4",
          priority: "high",
          title: "رصد رقبا روی ۲۰ کلمه طلایی",
          where: "GSC + SERP",
          why: "تنظیم اولویت ماه ۶–۷",
          done: false,
        },
        {
          id: "p5-a5",
          priority: "high",
          title: "گزارش ماه ۵ + جدول رتبه/impression · ۱۲۸/۲۰۶",
          where: "داشبورد",
          why: "P1 تا اینجا: ۷۵ از ۹۰",
          done: false,
        },
      ],
      checklist: [
        { id: "p5-c1", label: "۳۰ کیورد P1 ماه ۵ پوشش شد", done: false },
        { id: "p5-c2", label: "حداقل ۲ دارایی برند/لینک معتبر", done: false },
        { id: "p5-c3", label: "جدول رصد رقبا به‌روز", done: false },
        { id: "p5-c4", label: "گزارش ماه ۵ · ۱۲۸/۲۰۶", done: false },
      ],
    },
    6: {
      title: "فاز ۶ — ماه ۶: باقی P1 + شروع P2",
      period: "ماه ۶ · ۲۰ آذر تا ۱۹ دی ۱۴۰۵",
      status: "upcoming",
      goal: "۱۵ کیورد P1 باقی (۹۰/۹۰) + ۳۰ کیورد P2",
      kwTarget: { p0: 0, p1: 15, p2: 30, p3: 0, total: 45 },
      actions: [
        {
          id: "p6-a1",
          priority: "critical",
          title: "۱۵ کیورد P1 باقی‌مانده → بستن ۹۰/۹۰",
          where: "keywords.csv + وردپرس",
          why: "اتمام کامل باکت مهم",
          done: false,
        },
        {
          id: "p6-a2",
          priority: "critical",
          title: "۳۰ کیورد P2 دستهٔ اول (بلاگ تکمیلی / تقویت موجود)",
          where: "بلاگ",
          why: "شروع پوشش ۵۸ کلمه تکمیلی",
          done: false,
        },
        {
          id: "p6-a3",
          priority: "medium",
          title: "بازبینی کنیبال و لینک داخلی خوشه‌های جدید",
          where: "سایت",
          why: "جلوگیری از رقابت داخلی بعد از حجم محتوا",
          done: false,
        },
        {
          id: "p6-a4",
          priority: "high",
          title: "گزارش ماه ۶ · تجمعی ۱۷۳/۲۰۶",
          where: "داشبورد + GSC",
          why: "P0+P1 کامل · P2 نیمه‌راه",
          done: false,
        },
      ],
      checklist: [
        { id: "p6-c1", label: "P1 کامل: ۹۰/۹۰", done: false },
        { id: "p6-c2", label: "۳۰ کیورد P2 ماه ۶ پوشش شد", done: false },
        { id: "p6-c3", label: "بازبینی کنیبال خوشه‌ها", done: false },
        { id: "p6-c4", label: "گزارش ماه ۶ · ۱۷۳/۲۰۶", done: false },
      ],
    },
    7: {
      title: "فاز ۷ — ماه ۷: تکمیل P2/P3 + تحویل",
      period: "ماه ۷ · ۲۰ دی تا ۱۹ بهمن ۱۴۰۵",
      status: "upcoming",
      goal: "۲۸ کیورد P2 + ۵ کیورد P3 · Audit نهایی · ۲۰۶/۲۰۶",
      kwTarget: { p0: 0, p1: 0, p2: 28, p3: 5, total: 33 },
      actions: [
        {
          id: "p7-a1",
          priority: "critical",
          title: "۲۸ کیورد P2 باقی → بستن ۵۸/۵۸",
          where: "بلاگ / صفحات سبک",
          why: "اتمام باکت تکمیلی",
          done: false,
        },
        {
          id: "p7-a2",
          priority: "high",
          title: "۵ کیورد P3 → صفحه یا ریدایرکت هدفمند",
          where: "وردپرس",
          why: "پوشش کامل ۲۰۶ کیورد لیست",
          done: false,
        },
        {
          id: "p7-a3",
          priority: "high",
          title: "Audit کامل مجدد + مقایسه با baseline جولای ۲۰۲۶",
          where: "Cursor /seo audit + داشبورد",
          why: "اثبات پیشرفت ۷ ماهه",
          done: false,
        },
        {
          id: "p7-a4",
          priority: "high",
          title: "چک‌لیست نگهداری هفتگی/ماهانه برای تیم داخلی",
          where: "مستند تحویل",
          why: "ادامه بدون وابستگی کامل",
          done: false,
        },
        {
          id: "p7-a5",
          priority: "medium",
          title: "بستن بدهی‌های فنی باقی‌مانده",
          where: "وردپرس / هاست",
          why: "پاکسازی قبل از پایان قرارداد",
          done: false,
        },
        {
          id: "p7-a6",
          priority: "critical",
          title: "گزارش نهایی ۷ماهه · تأیید ۲۰۶/۲۰۶ + پیشنهاد تمدید",
          where: "داشبورد + PDF/Markdown",
          why: "تحویل رسمی قرارداد",
          done: false,
        },
      ],
      checklist: [
        { id: "p7-c1", label: "P2 کامل: ۵۸/۵۸", done: false },
        { id: "p7-c2", label: "P3 کامل: ۵/۵", done: false },
        { id: "p7-c3", label: "پوشش کیورد ۲۰۶/۲۰۶ تأیید شد", done: false },
        { id: "p7-c4", label: "Audit نهایی ثبت شد", done: false },
        { id: "p7-c5", label: "چک‌لیست نگهداری تحویل شد", done: false },
        { id: "p7-c6", label: "گزارش نهایی ۷ماهه", done: false },
      ],
    },
  },

  metaTargets: [
    {
      page: "صفحه اصلی",
      url: "/",
      title: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
      description:
        "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
      h1: "مشاوره رایگان کنکور در ذهن آتی",
    },
    {
      page: "درباره ما",
      url: "/about/",
      title: "درباره آکادمی ذهن آتی | دکتر زهرا جعفری",
      description:
        "آکادمی مشاوره کنکور ذهن آتی با مدیریت دکتر زهرا جعفری. ۲۰۰۰+ قبولی و ۵۰۰ رتبه دو و سه‌رقمی. اپلیکیشن اختصاصی.",
      h1: "درباره آکادمی ذهن آتی",
    },
    {
      page: "تماس",
      url: "/contact-us/",
      title: "تماس با ذهن آتی | مشاوره رایگان کنکور",
      description:
        "تماس با آکادمی ذهن آتی: ۰۲۱-۲۸۴۲۷۲۵۹. شعب اصفهان (وحید) و تهران (میدان فاطمی). مشاوره رایگان آنلاین.",
      h1: "تماس با ما",
    },
  ],
};

/* آرایه‌های تخت برای سازگاری با رندرر */
(function expandPhaseLists(D) {
  D.actions = [];
  const phases = Object.keys(D.phaseDetails || {})
    .map(Number)
    .sort((a, b) => a - b);
  for (const p of phases) {
    const det = D.phaseDetails[p];
    if (!det) continue;
    for (const a of det.actions || []) {
      D.actions.push(Object.assign({ phase: p }, a));
    }
  }
  D.week1Checklist = (D.phaseDetails[0] && D.phaseDetails[0].checklist) || [];
})(window.ZEHNATI_SEO);
