/* دادهٔ آنالیز SEO ذهن آتی — به‌روز: ۱۵ جولای ۲۰۲۶ / ۲۴ تیر ۱۴۰۵ */
window.ZEHNATI_SEO = {
  meta: {
    brand: "ذهن آتی",
    domain: "https://zehnati.ir/",
    manager: "دکتر زهرا جعفری",
    updatedAt: "2026-07-15",
    updatedAtFa: "۲۴ تیر ۱۴۰۵",
    phase: 1,
    phaseLabel: "فاز ۱ — Landingهای P0 (هفته ۲)",
    week: 2,
    planStartFa: "۱۴۰۵/۰۴/۲۰",
    planStartLabel: "۲۰ تیر ۱۴۰۵",
    planEndFa: "۱۴۰۵/۰۵/۱۶",
    planEndLabel: "۱۶ مرداد ۱۴۰۵",
    planWeeks: 4,
    planNote: "برنامه فشردهٔ ۱ ماهه — هر فاز = ۱ هفته",
  },
  score: {
    overall: 55,
    label: "در حال پیشرفت — فاز ۱: لندینگ‌های P0",
    breakdown: [
      { id: "tech", name: "فنی", score: 50, max: 100 },
      { id: "onpage", name: "آن‌پیج", score: 70, max: 100 },
      { id: "content", name: "محتوا", score: 44, max: 100 },
      { id: "local", name: "محلی", score: 60, max: 100 },
      { id: "conversion", name: "تبدیل / Landing", score: 35, max: 100 },
    ],
  },
  kpis: [
    { label: "صفحات ایندکس (هدف ۳۰روز)", current: "~۵", target: "۳۰+" },
    { label: "پست‌های بلاگ منتشرشده", current: "۳۳۲", target: "بهینه + CTA" },
    { label: "صفحات وردپرس", current: "۲۲", target: "۳۵+" },
    { label: "لندینگ P0 آماده‌شده", current: "۳", target: "۱۰+" },
  ],
  techStatus: [
    { id: "ssl", name: "HTTPS / SSL", status: "pass", detail: "فعال" },
    { id: "robots", name: "robots.txt", status: "pass", detail: "موجود؛ به sitemap_index.xml اشاره می‌کند (فعال)" },
    { id: "sitemap", name: "XML Sitemap", status: "pass", detail: "فعال (200) — sitemap_index.xml" },
    { id: "rankmath", name: "Rank Math", status: "pass", detail: "نصب شده" },
    { id: "analytics", name: "Analytics / GTM", status: "pass", detail: "GA4 از Rank Math — G-Y0GZ4B5T0Y" },
    { id: "litespeed", name: "LiteSpeed Cache", status: "pass", detail: "فعال" },
    { id: "h1", name: "H1 صفحه اصلی", status: "pass", detail: "مشاوره رایگان کنکور در ذهن آتی" },
    { id: "meta", name: "Meta Description", status: "pass", detail: "اختصاصی و بهینه — دیگر اسکرپ نیست" },
    { id: "about-h1", name: "H1 درباره ما", status: "pass", detail: "۱ H1 — درباره آکادمی ذهن آتی" },
    { id: "schema", name: "Schema محلی", status: "warn", detail: "LocalBusiness اصفهان هست؛ تهران/Person در فاز ۱" },
    { id: "landings", name: "Landingهای P0", status: "warn", detail: "فاز ۱ جاری — قیمت/آنلاین/شهر هنوز نه" },
  ],
  homepage: {
    titleNow: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر زهرا جعفری",
    titleTarget: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
    descNow:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    descTarget:
      "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
    h1Target: "مشاوره رایگان کنکور در ذهن آتی",
    schemas: ["ImageObject", "WebSite", "SearchAction", "WebPage", "Person", "Article"],
  },
  goldenKeywords: [
    { kw: "مشاوره رایگان کنکور", page: "/", status: "ok", note: "صفحه اصلی بهینه شد" },
    { kw: "مشاوره کنکور", page: "/مشاوره-کنکور/", status: "partial", note: "فاز ۱: کاهش ۱۷ H1 + هاب تجاری" },
    { kw: "بهترین مشاور کنکور اصفهان", page: "/بهترین-مشاور-کنکور-اصفهان/", status: "missing", note: "فاز ۱" },
    { kw: "برنامه ریزی کنکور", page: "/برنامه-ریزی-کنکور/", status: "partial", note: "فاز ۱–۲" },
    { kw: "مشاوره کنکور تجربی", page: "/مشاوره-کنکور-تجربی/", status: "ok", note: "موجود — اصلاح ساختار H1 در فاز ۱" },
    { kw: "قیمت مشاوره کنکور", page: "/قیمت-مشاوره-کنکور/", status: "missing", note: "فاز ۱ — اولویت" },
    { kw: "مشاوره آنلاین کنکور", page: "/مشاوره-آنلاین-کنکور/", status: "missing", note: "فاز ۱" },
    { kw: "چگونه پزشکی قبول شویم", page: "بلاگ", status: "partial", note: "فاز ۲" },
    { kw: "ثبت نام کلاس کنکور", page: "/ثبت-نام/", status: "partial", note: "فاز ۱" },
    { kw: "دکتر زهرا جعفری", page: "/about/", status: "ok", note: "Meta/Title + ۱ H1 OK" },
  ],
  keywordBuckets: [
    { id: "P0", label: "حیاتی", count: 53, action: "صفحه در هفته ۲ (فاز ۱)" },
    { id: "P1", label: "مهم", count: 90, action: "محتوا در هفته ۳ (فاز ۲)" },
    { id: "P2", label: "تکمیلی", count: 58, action: "هفته ۴ (فاز ۳)" },
    { id: "P3", label: "آینده", count: 5, action: "بعد از ماه اول" },
  ],
  existingPages: [
    { url: "/", title: "خانه" },
    { url: "/about/", title: "درباره ما" },
    { url: "/contact-us/", title: "ارتباط با ما" },
    { url: "/academic-counseling/", title: "ویس آموزشی" },
    { url: "/top-consultants/", title: "مشاورین برتر" },
    { url: "/satisfaction/", title: "رضایتمندی" },
    { url: "/webinars/", title: "وبینارها" },
    { url: "/expert/", title: "فرم ثبت‌نام" },
  ],

  /* —— برنامه ۴ هفته از ۱۴۰۵/۰۴/۲۰ —— */
  timeline: [
    {
      phase: 0,
      label: "فنی",
      weeks: "۱",
      dateRange: "۲۰–۲۶ تیر",
      status: "done",
      summary: "زیربنای فنی سایت آماده شد (GSC، GA4، Sitemap، Rank Math، Home/About).",
    },
    {
      phase: 1,
      label: "Landingهای P0",
      weeks: "۲",
      dateRange: "۲۷ تیر – ۲ مرداد",
      status: "active",
      summary: "ساخت و بهینه‌سازی لندینگ‌های تجاری حیاتی + اصلاح هاب مشاوره کنکور.",
    },
    {
      phase: 2,
      label: "محتوا و Silo",
      weeks: "۳",
      dateRange: "۳–۹ مرداد",
      status: "upcoming",
      summary: "مقالات P0، لینک داخلی Silo، تقویت E-E-A-T و نویسنده واقعی.",
    },
    {
      phase: 3,
      label: "گسترش",
      weeks: "۴",
      dateRange: "۱۰–۱۶ مرداد",
      status: "upcoming",
      summary: "صفحات محلی، GBP، CWV، و Submit نهایی در GSC.",
    },
  ],

  phaseDetails: {
    0: {
      title: "فاز ۰ — فنی و آماده‌سازی",
      period: "هفته ۱ · ۲۰–۲۶ تیر ۱۴۰۵",
      status: "done",
      goal: "سایت ایندکس‌پذیر، ابزار سنجش فعال، پایهٔ SEO آماده",
      actions: [
        {
          id: "p0-a1",
          priority: "critical",
          title: "رفع Sitemap 404",
          where: "Rank Math → Sitemap",
          why: "انجام شد — sitemap_index.xml = 200",
          done: true,
        },
        {
          id: "p0-a2",
          priority: "critical",
          title: "Submit Sitemap در GSC",
          where: "Google Search Console",
          why: "انجام شد — Success · صفحات کشف‌شده",
          done: true,
        },
        {
          id: "p0-a3",
          priority: "high",
          title: "اصلاح Title / Meta / H1 صفحه اصلی",
          where: "Rank Math Home",
          why: "انجام شد — مشاوره رایگان کنکور",
          done: true,
        },
        {
          id: "p0-a4",
          priority: "medium",
          title: "بهینه Meta برای /about/ و /contact-us/",
          where: "Rank Math",
          why: "انجام شد — Title/Meta + /about/ یک H1",
          done: true,
        },
        {
          id: "p0-a5",
          priority: "high",
          title: "نصب GA4 از Rank Math",
          where: "Rank Math → Analytics",
          why: "انجام شد — G-Y0GZ4B5T0Y در HTML",
          done: true,
        },
        {
          id: "p0-a6",
          priority: "medium",
          title: "کرون واقعی سرور (DISABLE_WP_CRON)",
          where: "cPanel Cron Jobs",
          why: "انجام شد — هر ۱۵ دقیقه wp-cron",
          done: true,
        },
      ],
      checklist: [
        { id: "w1-gsc", label: "ثبت Google Search Console", done: true },
        { id: "w1-ga4", label: "نصب Google Analytics 4", done: true },
        { id: "w1-sitemap", label: "رفع sitemap 404", done: true },
        { id: "w1-rankmath", label: "نصب/تنظیم Rank Math", done: true },
        { id: "w1-home-meta", label: "Title / Meta / H1 صفحه اصلی", done: true },
        { id: "w1-about", label: "بهینه درباره ما (Meta + ۱ H1)", done: true },
        { id: "w1-contact", label: "بهینه تماس با ما", done: true },
        { id: "w1-cron", label: "Cron واقعی روی هاست", done: true },
        { id: "w1-psi", label: "تست اولیه PageSpeed (ثبت شد)", done: true },
        { id: "w1-phase0-review", label: "بازبینی و بستن فاز ۰", done: true },
      ],
    },
    1: {
      title: "فاز ۱ — Landingهای P0",
      period: "هفته ۲ · ۲۷ تیر تا ۲ مرداد ۱۴۰۵",
      status: "active",
      goal: "۱۰+ لندینگ تجاری حیاتی زنده و قابل ایندکس",
      actions: [
        {
          id: "p1-a1",
          priority: "critical",
          title: "ساخت /قیمت-مشاوره-کنکور/",
          where: "صفحات → افزودن + Rank Math",
          why: "الان 404 — کلمه طلایی تجاری P0",
          done: false,
        },
        {
          id: "p1-a2",
          priority: "critical",
          title: "اصلاح هاب /مشاوره-کنکور/ (۱ H1 + محتوای تجاری)",
          where: "Elementor / قالب صفحه",
          why: "صفحه 200 است ولی ۱۷ H1 دارد",
          done: false,
        },
        {
          id: "p1-a3",
          priority: "high",
          title: "ساخت /مشاوره-آنلاین-کنکور/",
          where: "Landing جدید",
          why: "کلمه طلایی P0 — الان نیست",
          done: false,
        },
        {
          id: "p1-a4",
          priority: "high",
          title: "Landing اصفهان / بهترین مشاور کنکور اصفهان",
          where: "صفحه یا تبدیل مقاله",
          why: "سیگنال محلی اصفهان",
          done: false,
        },
        {
          id: "p1-a5",
          priority: "high",
          title: "Landing تهران + ثبت‌نام / پکیج",
          where: "وردپرس",
          why: "پوشش قیف تجاری",
          done: false,
        },
        {
          id: "p1-a6",
          priority: "medium",
          title: "کاهش H1 صفحه تجربی به ۱",
          where: "/مشاوره-کنکور-تجربی/",
          why: "الان ۱۷ H1 مثل آرشیو است",
          done: false,
        },
        {
          id: "p1-a7",
          priority: "high",
          title: "تعویض نویسنده fish-programmer → دکتر زهرا جعفری",
          where: "وردپرس کاربر / Rank Math",
          why: "E-E-A-T و Twitter author",
          done: false,
        },
        {
          id: "p1-a8",
          priority: "medium",
          title: "تکمیل Schema LocalBusiness + Person",
          where: "Rank Math Schema",
          why: "اصفهان کامل‌تر + تهران + Person دکتر جعفری",
          done: false,
        },
      ],
      checklist: [
        { id: "p1-c1", label: "صفحه قیمت مشاوره کنکور (200)", done: false },
        { id: "p1-c2", label: "هاب مشاوره کنکور با ۱ H1", done: false },
        { id: "p1-c3", label: "لندینگ مشاوره آنلاین", done: false },
        { id: "p1-c4", label: "لندینگ اصفهان", done: false },
        { id: "p1-c5", label: "لندینگ تهران یا ثبت‌نام", done: false },
        { id: "p1-c6", label: "نویسنده سایت = دکتر جعفری", done: false },
        { id: "p1-c7", label: "Schema Local + Person", done: false },
        { id: "p1-c8", label: "Submit صفحات جدید در GSC", done: false },
      ],
    },
    2: {
      title: "فاز ۲ — محتوا و Silo",
      period: "هفته ۳ · ۳–۹ مرداد ۱۴۰۵",
      status: "upcoming",
      goal: "محتوای ستون‌دار + لینک داخلی معنادار",
      actions: [
        {
          id: "p2-a1",
          priority: "high",
          title: "تقویت محتوای homepage (پوشش تجاری عمیق‌تر)",
          where: "صفحه اصلی Elementor",
          why: "هوم از نظر محتوا هنوز نازک است",
          done: false,
        },
        {
          id: "p2-a2",
          priority: "high",
          title: "مقاله P0: چگونه پزشکی قبول شویم (بازنویسی/تقویت)",
          where: "بلاگ",
          why: "کلمه طلایی اطلاعاتی",
          done: false,
        },
        {
          id: "p2-a3",
          priority: "high",
          title: "لینک داخلی از بلاگ به هاب‌های مشاوره/قیمت/رشته",
          where: "پست‌های کلیدی",
          why: "سilo و انتقال اعتبار",
          done: false,
        },
        {
          id: "p2-a4",
          priority: "medium",
          title: "هاب رشته ریاضی / انسانی تمیز (۱ H1)",
          where: "صفحات رشته",
          why: "هم‌تراز با تجربی",
          done: false,
        },
        {
          id: "p2-a5",
          priority: "medium",
          title: "برنامه ریزی کنکور + انتخاب رشته (صفحه اختصاصی)",
          where: "Landing یا اصلاح ریدایرکت‌های اشتباه",
          why: "URL تجاری نباید به مقاله نامرتبط برود",
          done: false,
        },
      ],
      checklist: [
        { id: "p2-c1", label: "Homepage محتوایی تقویت شد", done: false },
        { id: "p2-c2", label: "حداقل ۳ مقاله P0 بهینه", done: false },
        { id: "p2-c3", label: "لینک داخلی Silo روی ۱۰ پست کلیدی", done: false },
        { id: "p2-c4", label: "هاب رشته‌ها ساختار تمیز", done: false },
        { id: "p2-c5", label: "رفع ریدایرکت‌های اشتباه تجاری", done: false },
      ],
    },
    3: {
      title: "فاز ۳ — گسترش و تثبیت",
      period: "هفته ۴ · ۱۰–۱۶ مرداد ۱۴۰۵",
      status: "upcoming",
      goal: "محلی + سرعت + مانیتورینگ آماده تحویل ماه اول",
      actions: [
        {
          id: "p3-a1",
          priority: "high",
          title: "راه‌اندازی Google Business اصفهان",
          where: "business.google.com",
          why: "Map Pack و اعتماد محلی",
          done: false,
        },
        {
          id: "p3-a2",
          priority: "medium",
          title: "شروع GBP تهران (یا زمان‌بندی تأیید)",
          where: "Google Business",
          why: "شعبه دوم",
          done: false,
        },
        {
          id: "p3-a3",
          priority: "medium",
          title: "هدرهای امنیتی پایه (HSTS, XFO, nosniff)",
          where: "LiteSpeed / هاست",
          why: "یافته technical audit",
          done: false,
        },
        {
          id: "p3-a4",
          priority: "medium",
          title: "بهینه تصاویر (alt + فشرده‌سازی LCP)",
          where: "مدیا وردپرس",
          why: "۱۵/۱۶ تصویر بدون alt روی هوم",
          done: false,
        },
        {
          id: "p3-a5",
          priority: "high",
          title: "گزارش ماه اول + /seo audit مجدد",
          where: "داشبورد + Cursor",
          why: "اثبات پیشرفت فاز ۰→۳ در ۴ هفته",
          done: false,
        },
      ],
      checklist: [
        { id: "p3-c1", label: "GBP اصفهان ثبت/تأیید شده", done: false },
        { id: "p3-c2", label: "هدرهای امنیتی فعال", done: false },
        { id: "p3-c3", label: "alt تصاویر صفحه اصلی", done: false },
        { id: "p3-c4", label: "PageSpeed ثبت نهایی", done: false },
        { id: "p3-c5", label: "Audit مجدد + گزارش ماه اول", done: false },
      ],
    },
  },

  metaTargets: [
    {
      page: "صفحه اصلی",
      url: "/",
      title: "مشاوره رایگان کنکور | آکادمی ذهن آتی — دکتر جعفری",
      description:
        "مشاوره رایگان کنکور با ۹ سال سابقه و ۵۰۰+ رتبه برتر. شعب اصفهان و تهران + آنلاین سراسر کشور. همین الان ثبت‌نام کنید!",
      h1: "مشاوره رایگان کنکور در ذهن آتی",
    },
    {
      page: "درباره ما",
      url: "/about/",
      title: "درباره آکادمی ذهن آتی | دکتر زهرا جعفری",
      description:
        "آکادمی مشاوره کنکور ذهن آتی با مدیریت دکتر زهرا جعفری. ۲۰۰۰+ قبولی و ۵۰۰ رتبه دو و سه‌رقمی. اپلیکیشن اختصاصی.",
      h1: "درباره آکادمی ذهن آتی",
    },
    {
      page: "تماس",
      url: "/contact-us/",
      title: "تماس با ذهن آتی | مشاوره رایگان کنکور",
      description:
        "تماس با آکادمی ذهن آتی: ۰۲۱-۲۸۴۲۷۲۵۹. شعب اصفهان (وحید) و تهران (میدان فاطمی). مشاوره رایگان آنلاین.",
      h1: "تماس با ما",
    },
  ],
};

/* آرایه‌های تخت برای سازگاری با رندرر */
(function expandPhaseLists(D) {
  D.actions = [];
  for (const p of [0, 1, 2, 3]) {
    const det = D.phaseDetails[p];
    if (!det) continue;
    for (const a of det.actions) {
      D.actions.push(Object.assign({ phase: p }, a));
    }
  }
  D.week1Checklist = (D.phaseDetails[0] && D.phaseDetails[0].checklist) || [];
})(window.ZEHNATI_SEO);
